services:
  - type: web
    name: papervista-backend
    env: python
    plan: starter
    region: oregon

    runtime: python
    rootDir: backend
    buildCommand: "pip install --upgrade pip setuptools && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_BUILD_ISOLATION
        value: "false"
      - key: GEMINI_API_KEY
        fromSecret: GEMINI_API_KEY
      - key: FRONTEND_URL
        value: https://paper-vista-five.vercel.app 
